-
  branches:
    except:
      - release

  skip_tags: true

  configuration: Debug

  image: Visual Studio 2017

  build_script:
   # - cmd: msbuild /t:restore ./src/Grafana.Api.Client.sln
    #- cmd: msbuild /t:build /p:Configuration=Debug /v:Minimal ./src/Grafana.Api.Client.sln
    - cmd: dotnet restore -v m  ./src/Grafana.Api.Client.sln
    - cmd: dotnet build  -v m -c Debug ./src/Grafana.Api.Client.sln
    - cmd: dotnet pack -v m --include-symbols --no-build -o ../../artifacts /p:PackageVersion=%APPVEYOR_BUILD_VERSION%-beta ./src/Grafana.Api.Client/Grafana.Api.Client.csproj
   # - cmd: msbuild /t:pack /p:IncludeSymbols=true /p:Configuration=Debug /p:PackageOutputPath=../../artifacts ./src/Grafana.Api.Client/Grafana.Api.Client.csproj
    - cmd: dotnet pack -v m --include-symbols --no-build -o ../../artifacts /p:PackageVersion=%APPVEYOR_BUILD_VERSION%-beta ./src/Grafana.Shared/Grafana.Shared.csproj
   # - cmd: msbuild /t:pack /p:IncludeSymbols=true /p:Configuration=Debug /p:PackageOutputPath=../../artifacts ./src/Grafana.Shared/Grafana.Shared.csproj
  artifacts:
    - path: "./artifacts/*.*"
-
  branches:
    only:
      - release

  configuration: Release

  image: Visual Studio 2017

  build_script:
    - cmd: dotnet restore -v m  ./src/Grafana.Api.Client.sln
    - cmd: dotnet build  -v m -c Release ./src/Grafana.Api.Client.sln
    - cmd: dotnet pack -v m --include-symbols --no-build -o ../../artifacts ./src/Grafana.Api.Client/Grafana.Api.Client.csproj
    - cmd: dotnet pack -v m --include-symbols --no-build -o ../../artifacts ./src/Grafana.Shared/Grafana.Shared.csproj
      
  artifacts:
    - path: "./artifacts/*.nupkg"

  deploy:
    provider: NuGet
    api_key:
      secure: OL1e2rPl7pvWKU5NktIlh15AeO1VKbiRhrMnvBsDSJazk1LqH967R7lTymVGle9N
      skip_symbols: false
      artifact: /.*\.nupkg/
